// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// equivalence_rcpp
IntegerVector equivalence_rcpp(IntegerVector a, IntegerVector b, int n);
RcppExport SEXP _reclin2_equivalence_rcpp(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(equivalence_rcpp(a, b, n));
    return rcpp_result_gen;
END_RCPP
}
// greedy_rcpp
LogicalVector greedy_rcpp(IntegerVector x, IntegerVector y, NumericVector w, bool include_ties);
RcppExport SEXP _reclin2_greedy_rcpp(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP include_tiesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< bool >::type include_ties(include_tiesSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_rcpp(x, y, w, include_ties));
    return rcpp_result_gen;
END_RCPP
}
// greedy_nm_rcpp
LogicalVector greedy_nm_rcpp(IntegerVector x, IntegerVector y, NumericVector w, int n, int m);
RcppExport SEXP _reclin2_greedy_nm_rcpp(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_nm_rcpp(x, y, w, n, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_reclin2_equivalence_rcpp", (DL_FUNC) &_reclin2_equivalence_rcpp, 3},
    {"_reclin2_greedy_rcpp", (DL_FUNC) &_reclin2_greedy_rcpp, 4},
    {"_reclin2_greedy_nm_rcpp", (DL_FUNC) &_reclin2_greedy_nm_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_reclin2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
