# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

equivalence_rcpp <- function(a, b, n) {
    .Call('_reclin2_equivalence_rcpp', PACKAGE = 'reclin2', a, b, n)
}

greedy_rcpp <- function(x, y, w, include_ties = FALSE) {
    .Call('_reclin2_greedy_rcpp', PACKAGE = 'reclin2', x, y, w, include_ties)
}

greedy_nm_rcpp <- function(x, y, w, n = 1L, m = 1L) {
    .Call('_reclin2_greedy_nm_rcpp', PACKAGE = 'reclin2', x, y, w, n, m)
}

